In [8]:
#DATA IMPUTATION

In [13]:
#mean with pandas
import pandas as pd

df = pd.DataFrame({
    'Age': [25, 30, None, 40, 35],
    'Experience': [2, 5, 3, None, 7]
})

df['Age'] = df['Age'].fillna(df['Age'].mean())
df['Experience'] = df['Experience'].fillna(df['Experience'].mean())

print(df)

    Age  Experience
0  25.0        2.00
1  30.0        5.00
2  32.5        3.00
3  40.0        4.25
4  35.0        7.00


In [14]:
#with imputer mean
from sklearn.impute import SimpleImputer
import pandas as pd

df = pd.DataFrame({
    'Age': [25, 30, None, 40, 35],
    'Experience': [2, 5, 3, None, 7]
})

imputer = SimpleImputer(strategy='mean')
df_imputed = imputer.fit_transform(df)

print(df_imputed)


[[25.    2.  ]
 [30.    5.  ]
 [32.5   3.  ]
 [40.    4.25]
 [35.    7.  ]]


In [15]:
#median with pandas
import pandas as pd

df = pd.DataFrame({
    'Age': [25, 30, None, 40, 100],
    'Experience': [2, 5, 3, None, 7]
})

df['Age'] = df['Age'].fillna(df['Age'].median())
df['Experience'] = df['Experience'].fillna(df['Experience'].median())

print(df)

     Age  Experience
0   25.0         2.0
1   30.0         5.0
2   35.0         3.0
3   40.0         4.0
4  100.0         7.0


In [16]:
#median with imputer
from sklearn.impute import SimpleImputer
import pandas as pd

df = pd.DataFrame({
    'Age': [25, 30, None, 40, 100],
    'Experience': [2, 5, 3, None, 7]
})

imputer = SimpleImputer(strategy='median')
df_imputed = imputer.fit_transform(df)

print(df_imputed)


[[ 25.   2.]
 [ 30.   5.]
 [ 35.   3.]
 [ 40.   4.]
 [100.   7.]]


In [19]:
#mode with pandas
import pandas as pd

df = pd.DataFrame({
    'Department': ['IT', 'HR', 'IT', 'Finance', None],
    'City': ['Vadodara', 'Ahmedabad', None, 'Vadodara', 'Vadodara']
})

df['Department'] = df['Department'].fillna(df['Department'].mode()[0])
df['City'] = df['City'].fillna(df['City'].mode()[0])

print(df)


  Department       City
0         IT   Vadodara
1         HR  Ahmedabad
2         IT   Vadodara
3    Finance   Vadodara
4         IT   Vadodara


In [20]:
#mode with imputer
from sklearn.impute import SimpleImputer
import pandas as pd

df = pd.DataFrame({
    'Department': ['IT', 'HR', 'IT', 'Finance', None],
    'City': ['Vadodara', 'Ahmedabad', None, 'Vadodara', 'Vadodara']
})

imputer = SimpleImputer(strategy='most_frequent')
df_imputed = imputer.fit_transform(df)

print(df_imputed)


[['IT' 'Vadodara']
 ['HR' 'Ahmedabad']
 ['IT' None]
 ['Finance' 'Vadodara']
 [None 'Vadodara']]


In [21]:
#constant with pandas
import pandas as pd

df = pd.DataFrame({
    'Age': [25, None, 30, 40],
    'Department': ['IT', 'HR', None, 'Finance']
})

df['Age'] = df['Age'].fillna(-1)
df['Department'] = df['Department'].fillna('Unknown')

print(df)


    Age Department
0  25.0         IT
1  -1.0         HR
2  30.0    Unknown
3  40.0    Finance


In [22]:
#constant with imputer
from sklearn.impute import SimpleImputer
import pandas as pd

df = pd.DataFrame({
    'Age': [25, None, 30, 40],
    'Department': ['IT', 'HR', None, 'Finance']
})

num_imputer = SimpleImputer(strategy='constant', fill_value=-1)
cat_imputer = SimpleImputer(strategy='constant', fill_value='Unknown')

df[['Age']] = num_imputer.fit_transform(df[['Age']])
df[['Department']] = cat_imputer.fit_transform(df[['Department']])

print(df)


    Age Department
0  25.0         IT
1  -1.0         HR
2  30.0       None
3  40.0    Finance


In [25]:
#KNN with pandas
#there is no feature

In [28]:
#KNN with imputer
import pandas as pd
from sklearn.impute import KNNImputer
from sklearn.preprocessing import StandardScaler

# Dataset
df = pd.DataFrame({
    'Age': [25, 30, 28, 40, 35],
    'Experience': [2, 5, 4, 8, 6],
    'Salary': [30000, 45000, None, 60000, 55000]
})

# Step 1: Scale data
scaler = StandardScaler()
df_scaled = scaler.fit_transform(df)

# Step 2: KNN Imputation
imputer = KNNImputer(n_neighbors=2)
df_imputed_scaled = imputer.fit_transform(df_scaled)

# Step 3: Inverse scaling
df_imputed = scaler.inverse_transform(df_imputed_scaled)

print(df_imputed)


[[2.50e+01 2.00e+00 3.00e+04]
 [3.00e+01 5.00e+00 4.50e+04]
 [2.80e+01 4.00e+00 3.75e+04]
 [4.00e+01 8.00e+00 6.00e+04]
 [3.50e+01 6.00e+00 5.50e+04]]


In [41]:
#Label encoding
le = LabelEncoder()
le.fit(["paris", "paris", "tokyo", "amsterdam"])
list(le.classes_)
le.transform(["tokyo", "tokyo", "paris"])
# list(le.inverse_transform([2, 2, 1]))

array([2, 2, 1])

In [42]:
#onehot
enc = OneHotEncoder(handle_unknown='ignore')
X = [['Male', 1], ['Female', 3], ['Female', 2]]
enc.fit(X)
enc.categories_
enc.transform([['Female', 1], ['Male', 4]]).toarray()
# enc.inverse_transform([[0, 1, 1, 0, 0], [0, 0, 0, 1, 0]])
# enc.get_feature_names_out(['gender', 'group'])

array([[1., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [43]:
#ordinal
from sklearn.preprocessing import OrdinalEncoder
enc = OrdinalEncoder()
X = [['Male', 1], ['Female', 3], ['Female', 2]]
enc.fit(X)
enc.categories_
enc.transform([['Female', 3], ['Male', 1]])
#enc.inverse_transform([[1, 0], [0, 1]])

array([[0., 2.],
       [1., 0.]])

In [45]:
#TargetEncoder
import pandas as pd

df = pd.DataFrame({
    'Department': ['IT', 'HR', 'IT', 'Finance', 'HR'],
    'Salary': [30000, 45000, 35000, 60000, 50000]
})

mean_encoding = df.groupby('Department')['Salary'].mean()

df['Dept_Target_Encoded'] = df['Department'].map(mean_encoding)

print(df)

  Department  Salary  Dept_Target_Encoded
0         IT   30000              32500.0
1         HR   45000              47500.0
2         IT   35000              32500.0
3    Finance   60000              60000.0
4         HR   50000              47500.0


In [46]:
#Frequency
import pandas as pd

df = pd.DataFrame({
    'City': ['Vadodara', 'Ahmedabad', 'Vadodara', 'Surat', 'Vadodara', 'Ahmedabad']
})

freq_map = df['City'].value_counts()

df['City_Freq_Encoded'] = df['City'].map(freq_map)

print(df)

        City  City_Freq_Encoded
0   Vadodara                  3
1  Ahmedabad                  2
2   Vadodara                  3
3      Surat                  1
4   Vadodara                  3
5  Ahmedabad                  2


In [47]:
#pipeline
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression

# Dataset
df = pd.DataFrame({
    'Age': [25, 30, None, 40],
    'Department': ['IT', 'HR', 'IT', 'HR'],
    'Salary': [30000, 45000, 35000, 60000]
})

X = df[['Age', 'Department']]
y = df['Salary']

# Separate columns
num_cols = ['Age']
cat_cols = ['Department']

# Pipelines
num_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='mean'))
])

cat_pipeline = Pipeline([
    ('encoder', OneHotEncoder())
])

# Column Transformer
preprocessor = ColumnTransformer([
    ('num', num_pipeline, num_cols),
    ('cat', cat_pipeline, cat_cols)
])

# Final Pipeline
model_pipeline = Pipeline([
    ('preprocessing', preprocessor),
    ('model', LinearRegression())
])

# Train
model_pipeline.fit(X, y)


Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer())]),
                                                  ['Age']),
                                                 ('cat',
                                                  Pipeline(steps=[('encoder',
                                                                   OneHotEncoder())]),
                                                  ['Department'])])),
                ('model', LinearRegression())])

In [52]:
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import Normalizer
ct = ColumnTransformer(
    [("norm1", Normalizer(), [0, 1]),
     ("norm2", Normalizer(), slice(2, 4))])
X = np.array([[0., 1., 2., 2.],
              [1., 1., 0., 1.]])
# Normalizer scales each row of X to unit norm. A separate scaling
# is applied for the two first and two last elements of each
# row independently.
ct.fit_transform(X)

array([[0.        , 1.        , 0.70710678, 0.70710678],
       [0.70710678, 0.70710678, 0.        , 1.        ]])

In [55]:
#Normalization
from sklearn.preprocessing import MinMaxScaler
import pandas as pd
data = pd.DataFrame({
'Age': [20, 25, 30, 35, 40],
'Salary': [20000, 40000, 60000,
80000, 100000]
})
scaler = MinMaxScaler()
normalized = scaler.fit_transform(data)
normalized

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [0.75, 0.75],
       [1.  , 1.  ]])

In [56]:
#Standardization
from sklearn.preprocessing import StandardScaler
import pandas as pd
data = pd.DataFrame({
'Age': [20, 25, 30, 35, 40],
'Salary': [20000, 40000, 60000,
80000, 100000]
})
scaler = StandardScaler()
standardized = scaler.fit_transform(data)
# View the transformed data
print(pd.DataFrame(
standardized,
columns=['Age', 'Salary']
))

        Age    Salary
0 -1.414214 -1.414214
1 -0.707107 -0.707107
2  0.000000  0.000000
3  0.707107  0.707107
4  1.414214  1.414214
